### ISSUE TITLE
TestRenderOpenshiftSDN failed

### ISSUE THREAD

**Issue by zshi-redhat** [openshift/openshift-network-operator#7]
"renderOpenshiftSDN" in openshift_sdn_test.go is evaluating the object len of "../../manifests/network/openshift-sdn/dummy.yaml" instead of given "OpenshiftSDNConfig", this causes unit test failure as below:

--- FAIL: TestRenderOpenshiftSDN (0.01s)
	testing_t_support.go:22: 
			/home/zshi/git/golang/src/github.com/openshift/openshift-network-operator/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ed
		github.com/openshift/openshift-network-operator/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc420380b00, 0x1247ee0, 0xc4203aa978, 0x0, 0x0, 0x0, 0x1256620)
			/home/zshi/git/golang/src/github.com/openshift/openshift-network-operator/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xae
		github.com/openshift/openshift-network-operator/pkg/operator.TestRenderOpenshiftSDN(0xc42040c1e0)
			/home/zshi/git/golang/src/github.com/openshift/openshift-network-operator/pkg/operator/openshift_sdn_test.go:36 +0x335
		testing.tRunner(0xc42040c1e0, 0x11cf248)
			/usr/local/go/src/testing/testing.go:777 +0xd0
		created by testing.(*T).Run
			/usr/local/go/src/testing/testing.go:824 +0x2e0
		
		Expected
		    <[]*unstructured.Unstructured | len:2, cap:2>: [
		        {
		            Object: {
		                "apiVersion": "apps/v1",
		                "kind": "Deployment",
		                "metadata": {
		                    "name": "dummy",
		                    "namespace": "default",
		                },
		                "spec": {
		                    "selector": {
		                        "matchLabels": {"app": "dummy"},
		                    },
		                    "template": {
		                        "metadata": {
		                            "labels": {"app": "dummy"},
		                        },
		                        "spec": {
		                            "containers": [
		                                {
		                                    "command": [
		                                        "/bin/sh",
		                                        "-c",
		                                        "while true; do echo dummy-dep-1; sleep 10; done",
		                                    ],
		                                    "image": "busybox",
		                                    "name": "dummy",
		                                },
		                            ],
		                        },
		                    },
		                },
		            },
		        },
		        {
		            Object: {
		                "apiVersion": "apps/v1beta2",
		                "kind": "DaemonSet",
		                "metadata": {
		                    "labels": {"app": "dummy-ds"},
		                    "name": "dummy-ds",
		                    "namespace": "default",
		                },
		                "spec": {
		                    "selector": {
		                        "matchLabels": {"app": "dummy-ds"},
		                    },
		                    "template": {
		                        "metadata": {
		                            "labels": {"app": "dummy-ds"},
		                        },
		                        "spec": {
		                            "containers": [
		                                {
		                                    "command": [
		                                        "/bin/sh",
		                                        "-c",
		                                        "while true; do echo dummy-ds-1; sleep 10; done",
		                                    ],
		                                    "image": "busybox",
		                                    "name": "dummy",
		                                },
		                            ],
		                        },
		                    },
		                    "updateStrategy": {
		                        "rollingUpdate": {"maxUnavailable": 1},
		                        "type": "RollingUpdate",
		                    },
		                },
		            },
		        },
		    ]
		to have length 1
FAIL
exit status 1
FAIL	github.com/openshift/openshift-network-operator/pkg/operator	0.017s

**Comment by squeed** [comment]
Fixed in #9, thanks.
